### ISSUE TITLE
Cannot find module 'to2'

### ISSUE THREAD

**Issue by hollowdoor** [m59peacemaker/node-tap-dapper#1]
I'm getting this error for some reason.

The error appears to be coming from [tap-form-synopsis](https://github.com/m59peacemaker/node-tap-form-synopsis) module. Though that module doesn't have a dependency on `to2` module in it's package.json.

I'm on Linux using Node version 7.5.

```
Error: Cannot find module 'to2'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<pathname>/node_modules/tap-form-synopsis/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

It's a mystery to me. Maybe this issue should be moved to tap-form-synopsis?

**Comment by m59peacemaker** [comment]
Hey there. My streaming TAP modules are on the back burner for the moment. I made them all to accomplish a goal that I don't have time for just yet. They all need a lot of refactoring. I'm not very happy with node's streams, or especially the way that I used them. So, I wouldn't use this for now. [tap-spec](https://www.npmjs.com/package/tap-spec) is nearly the same. I suggest that.

That said, the issue is that I forgot to include `to2` in the package.json for `tap-form-synoposis`.

**Comment by hollowdoor** [comment]
Ok. I'm curious. What don't you like about node streams? It's alright if you don't want to answer, or if you don't have the time to explain.

**Comment by m59peacemaker** [comment]
I'm glad to discuss! The node stream API is complex. It can be tricky to compose them. Here's an example that causes me stress:

```js
const foo = streamA().pipe(streamB()).pipe(process.stdout)
foo.write('a')
foo.push('b')

const bar = streamA()
bar.pipe(streamB()).pipe(process.stdout)
bar.write('a')
bar.write('b')
```

Without trying it, I can't tell you how those examples will behave. Stream can be made very simple and understandable by applying functional programming principles. I want to take some time to look into converting node streams into functors and composing that way. Because functors implement `map`, a library like `through2` wouldn't be needed to transform streams.

For some more perspective, consider how easy this is:

```js
['foo', 'bar']
  .map(v => v + 'd') // ['food', 'bard']
  .sort() // ['bard', 'food']
  .join(' ') // 'bard food'
  .repeat(2) // 'bard food bard food'
```

We can make creating, interacting with, and composing node streams that simple, so I want to!

**Comment by hollowdoor** [comment]
I see. That is a noble thought.

Some others have thought similarly. [overflow](https://github.com/avinoamr/overflow), [highlandjs](http://highlandjs.org/).

I don't know if those libraries would be considered traditional functors, but they try. Especially highland. Looking at the source of highlandjs it looks quite complicated. Overflow is more like an array in general, and simpler, but isn't as general as highland with it's overloaded constructor, and tons of methods. Highland looks like it's also meant to replace the async library.

I too am working on a composable interface for streams. I was testing it. That's where I found the error in `tap-dapper`. :)

Seems like everything is mixed up, and intertwined.

**Comment by m59peacemaker** [comment]
I'm looking at stuff like this:

https://github.com/fantasyland/fantasy-land
https://github.com/rpominov/static-land
https://github.com/ramda/ramda-fantasy
https://github.com/paldepind/flyd

**Comment by hollowdoor** [comment]
Does that mean you're thinking of function first--value last parameters? Like `map(fn, 'some value');`?

Are you going to try to make something compatible with ramda, or fantasy-land?

Looks like there was some talk of ramda to highland integration some time ago. An empty ramda-highland repo was made years ago, but hasn't had any activity since.

**Comment by m59peacemaker** [comment]
It would be fantasy or static land complaint. The thing about functors is that you can keep things minimal and they'll just work with libraries like Ramda out of the box. I don't think that's how highland works.

**Comment by hollowdoor** [comment]
Yeah highland uses dot composition. It has map, partial, and curry, but from what I can tell it's not simply a functor. I think it might be trying to treat stream instances as functors. It returns another instance of itself through a `createChild` method that's called from a `consume` method. `map` wraps `consume`. There's a `pull` method called from `createChild` which looks like it might be the actual functor `map` getting a single value each iteration. I wonder if the nature of streams dictated that design.

I've been trying to read highland source to get a better idea of how caolan did it. My knowledge of streams, and functional programming is not very good so it can be somewhat hard reading for me.
